### ISSUE TITLE
Progress indicator for get command

### ISSUE THREAD

**Issue by qzb** [g2a-com/klio#7]
Currently `klio get` doesn't indicate progress when downloading commands. Usually it's not an issue, but sometimes it stucks for quite a long time (and ruins user experience).

**Comment by wopol** [comment]
is it nice enough? Or we want something simpler without any dependencies ?

![out](https://user-images.githubusercontent.com/9054681/99823655-ee49e700-2b54-11eb-898b-466d653cfb4b.gif)

**Comment by qzb** [comment]
Oh, it's very nice :) I have no issue with dependencies.
